#baseURL = "https://stahnma.github.io/dashnewver.org"
baseURL = "/"
languageCode = "en-us"
title = "dashnewver.org"
theme = "landingpage"
description = "Versioning with simplicity."
publishDir = "docs"
